version: '3.8'
services:
  git-server:
    image: emarcs/nginx-git:latest
    container_name: meuse-git-server
    ports:
      - "${GIT_PORT:-8180}:80"
    volumes:
      - ./git-data:/srv/git
      - ./git-data/htpasswd:/srv/htpasswd
      - ./git-data/default.conf:/etc/nginx/conf.d/default.conf
    environment:
      - GIT_POSTBUFFER=1048576
    restart: unless-stopped

  # Optional helper service to list repositories (not started automatically)
  git-init:
    image: alpine/git
    entrypoint: [ "/bin/sh", "-c" ]
    command: "mkdir -p /srv/git && cd /srv/git && sleep infinity"
    volumes:
      - ./git-data:/srv/git
    stdin_open: true
    tty: true
