version: '3.8'

services:
  postgres:
    image: postgres:13-alpine
    container_name: meuse-postgres-dev
    restart: unless-stopped
    environment:
      POSTGRES_USER: meuse
      POSTGRES_PASSWORD: meuse_password
      POSTGRES_DB: meuse
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U meuse" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: