services:
  postgres:
    image: postgres:14.4
    container_name: meuse-postgres
    environment:
      POSTGRES_DB: meuse
      POSTGRES_USER: meuse
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - meuse_network
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U meuse -d meuse" ]
      interval: 30s
      timeout: 10s
      retries: 5

  meuse:
    image: mokhtarabadi/meuse:latest
    container_name: meuse-app
    environment:
      - MEUSE_CONFIGURATION=/app/config/config.yaml
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - MEUSE_FRONTEND_SECRET=${MEUSE_FRONTEND_SECRET}
      - DOMAIN=${DOMAIN}
    volumes:
      - ./config:/app/config:ro
      - ./crates:/app/crates
      - ./index:/app/index
      - ./git-repos:/app/git-repos
      - meuse_logs:/app/logs
    networks:
      - meuse_network
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8855/healthz" ]
      interval: 30s
      timeout: 10s
      retries: 5

  nginx:
    image: nginx:alpine
    container_name: meuse-nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - meuse_logs:/var/log/nginx
    ports:
      - "8080:80"
    networks:
      - meuse_network
    depends_on:
      - meuse
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost/healthz" ]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  postgres_data:
  meuse_logs:

networks:
  meuse_network:
    driver: bridge