version: '3.8'
services:
  postgres:
    image: postgres:14.4
    container_name: meuse-postgres
    restart: unless-stopped
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-meuse}
      POSTGRES_USER: ${POSTGRES_USER:-meuse}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-meuse}
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-meuse} -d ${POSTGRES_DB:-meuse}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  git-server:
    image: emarcs/nginx-git:latest
    container_name: meuse-git-server
    restart: unless-stopped
    ports:
      - "${GIT_PORT:-8180}:80"
    volumes:
      - ./git-data:/srv/git
      - ./git-data/htpasswd:/etc/nginx/.htpasswd
      - ./docker/git/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/git/default.conf:/etc/nginx/conf.d/default.conf:ro
    environment:
      - GIT_POSTBUFFER=1048576

  meuse:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: meuse-app
    restart: unless-stopped
    ports:
      - "${MEUSE_PORT:-8855}:8855"
    volumes:
      - ./git-data:/app/git-data
      - ./crates:/app/crates
      - ./config/docker-config.yaml:/app/config/config.yaml:ro
    environment:
      - MEUSE_CONFIGURATION=/app/config/config.yaml
      - JAVA_OPTS=${MEUSE_JAVA_OPTS:--Xmx512m}
    entrypoint: [ "/bin/sh", "-c", "mkdir -p /app/config && exec java $${JAVA_OPTS} -jar /app/meuse.jar" ]
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8855/healthz" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    depends_on:
      - postgres
      - git-server

volumes:
  pg_data:
