services:
  postgres:
    image: postgres:14.4
    container_name: meuse-postgres
    environment:
      POSTGRES_DB: meuse
      POSTGRES_USER: meuse
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-meuse_secure_password}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - meuse_network
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U meuse -d meuse" ]
      interval: 30s
      timeout: 10s
      retries: 5

  meuse:
    image: mcorbin/meuse:latest
    container_name: meuse-app
    environment:
      - MEUSE_CONFIGURATION=/app/config/config.yaml
    volumes:
      - ./config:/app/config:ro
      - meuse_crates:/app/crates
      - .:/app/index:ro
      - ./logs:/app/logs
      - ./temp-registry:/host/temp-registry:ro
    ports:
      - "8855:8855"
    networks:
      - meuse_network
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8855/healthz" ]
      interval: 30s
      timeout: 10s
      retries: 5

  nginx:
    image: nginx:alpine
    container_name: meuse-nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./logs/nginx:/var/log/nginx
    ports:
      - "80:80"
      - "443:443"
    networks:
      - meuse_network
    depends_on:
      - meuse
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost/healthz" ]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  postgres_data:
  meuse_crates:
  meuse_index:

networks:
  meuse_network:
    driver: bridge