services:
  postgres:
    image: postgres:14.4
    container_name: meuse-postgres
    restart: unless-stopped
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-meuse}
      POSTGRES_USER: ${POSTGRES_USER:-meuse}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-meuse}
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-meuse} -d ${POSTGRES_DB:-meuse}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  git-server:
    image: emarcs/nginx-git:latest
    container_name: meuse-git-server
    restart: unless-stopped
    ports:
      - "${GIT_PORT:-8180}:80"
    environment:
      GIT_POSTBUFFER: 1048576
    volumes:
      - meuse_git_data:/srv/git
      - type: bind
        source: ./git-data/htpasswd
        target: /etc/nginx/.htpasswd
        read_only: true
      - ./docker/git/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/git/default.conf:/etc/nginx/conf.d/default.conf:ro

  meuse:
    image: ghcr.io/mokhtarabadi/meuse:latest
    container_name: meuse-app
    restart: unless-stopped
    ports:
      - "${MEUSE_PORT:-8855}:8855"
    volumes:
      - meuse_git_data:/app/git-data
      - meuse_crates:/app/crates
      - ./config/docker-config.yaml:/app/config/config.yaml:ro
    environment:
      MEUSE_CONFIGURATION: /app/config/config.yaml
      JAVA_OPTS: ${MEUSE_JAVA_OPTS:--Xmx512m}
      # Domain and URLs
      DOMAIN: ${DOMAIN:-localhost}
      REGISTRY_URL: ${REGISTRY_URL:-http://localhost:8855}
      CARGO_API_URL: ${CARGO_API_URL:-http://localhost:8855/api/v1/crates}
      # Git configuration
      GIT_USER: ${GIT_USER}
      GIT_PASSWORD: ${GIT_PASSWORD}
      GIT_INDEX_PATH: ${GIT_INDEX_PATH}
      GIT_TARGET: ${GIT_TARGET}
      GIT_INDEX_URL: http://git-server/myindex.git
      # Database configuration
      POSTGRES_DB: ${POSTGRES_DB:-meuse}
      POSTGRES_USER: ${POSTGRES_USER:-meuse}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-meuse}
      POSTGRES_HOST: postgres
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
      POSTGRES_POOL_SIZE: ${POSTGRES_POOL_SIZE:-10}
      # Meuse configuration
      MEUSE_PORT: ${MEUSE_PORT:-8855}
      MEUSE_LOG_LEVEL: ${MEUSE_LOG_LEVEL:-info}
      # Crate storage
      CRATES_PATH: ${CRATES_PATH}
      # Frontend settings
      FRONTEND_ENABLED: ${FRONTEND_ENABLED:-true}
      FRONTEND_PUBLIC: ${FRONTEND_PUBLIC:-true}
      FRONTEND_SECRET: ${FRONTEND_SECRET}
      # Initial users
      ADMIN_USER: ${ADMIN_USER}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      TECH_USER: ${TECH_USER}
      TECH_PASSWORD: ${TECH_PASSWORD}
      READ_USER: ${READ_USER}
      READ_PASSWORD: ${READ_PASSWORD}
    # Using Dockerfile's ENTRYPOINT and CMD
    # The entrypoint.sh handles Git init and injects JAVA_OPTS
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8855/healthz" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    depends_on:
      - postgres
      - git-server

volumes:
  pg_data:
  meuse_git_data:
  meuse_crates:
