version: '3.8'
services:
  postgres:
    image: postgres:14.4
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: meuse
      POSTGRES_USER: meuse
      POSTGRES_PASSWORD: meuse
    volumes:
      - pg_data:/var/lib/postgresql/data

  git-server:
    image: emarcs/nginx-git:latest
    container_name: meuse-git-server
    ports:
      - "${GIT_PORT:-8180}:80"
    volumes:
      - ./git-data:/srv/git
      - ./git-data/htpasswd:/etc/nginx/.htpasswd
      - ./docker/git/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/git/default.conf:/etc/nginx/conf.d/default.conf:ro
    environment:
      - GIT_POSTBUFFER=1048576
    restart: unless-stopped
volumes:
  pg_data:

  # Git HTTP server service (nginx + git-http-backend)
  # This service hosts git repositories over HTTP with basic auth
