version: '3.8'
services:
  postgres:
    image: postgres:14.4
    container_name: meuse-postgres
    restart: unless-stopped
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-meuse}
      POSTGRES_USER: ${POSTGRES_USER:-meuse}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-meuse}
    volumes:
      - pg_data:/var/lib/postgresql/data

  git-server:
    image: emarcs/nginx-git:latest
    container_name: meuse-git-server
    restart: unless-stopped
    ports:
      - "${GIT_PORT:-8180}:80"
    volumes:
      - ./git-data:/srv/git
      - ./git-data/htpasswd:/etc/nginx/.htpasswd
      - ./docker/git/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/git/default.conf:/etc/nginx/conf.d/default.conf:ro
    environment:
      - GIT_POSTBUFFER=1048576

  meuse:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: meuse-app
    restart: unless-stopped
    ports:
      - "${MEUSE_PORT:-8855}:8855"
    volumes:
      - ./git-data:/app/git-data
      - ./crates:/app/crates
      - ./config/docker-config.yaml:/app/config/config.yaml:ro
    environment:
      - MEUSE_CONFIGURATION=/app/config/config.yaml
      - JAVA_OPTS=${MEUSE_JAVA_OPTS:--Xmx512m}
    depends_on:
      - postgres
      - git-server

volumes:
  pg_data:
