# PostgreSQL database configuration
database:
  user: "meuse"
  password: "meuse_password"
  host: "localhost"
  port: 5432
  name: "meuse"
  max-pool-size: 10

# HTTP server configuration
http:
  address: "0.0.0.0"  # Listen on all interfaces for Docker
  port: 8855

# Logging configuration
logging:
  level: info
  console:
    encoder: json
  overrides:
    org.eclipse.jetty: info
    com.zaxxer.hikari.pool.HikariPool: info
    org.apache.http: error
    io.netty.buffer.PoolThreadCache: error
    org.eclipse.jgit.internal.storage.file.FileSnapshot: info

# Git index configuration - Using JGit with credentials
metadata:
  type: "jgit"  # Use JGit instead of shell Git
  path: "/home/mohammad/Develop/Projects/meuse/data/index"
  target: "master"
  url: "http://localhost:8080/index.git"
  username: "git"
  password: "gitpassword"

# Crate storage configuration
crate:
  store: filesystem
  path: "/home/mohammad/Develop/Projects/meuse/data/crates"

# Frontend configuration
frontend:
  enabled: true
  public: false
  secret: "abcdef1234567890abcdef1234567890abcdef12"

# Initial users configuration
initial-users:
  # Admin user
  - name: "admin"
    password: "admin_password"
    description: "Administrator account"
    role: "admin"
    active: true

  # Technical user
  - name: "tech"
    password: "tech_password"
    description: "Technical account for CI/CD"
    role: "tech"

  # Read-only user
  - name: "readonly"
    password: "readonly_password"
    description: "Read-only account"
    role: "read-only"